[package]
name = "ping"
version = "0.1.0"
authors = ["Sergey Zolotarev <sryze@protonmail.com>"]
edition = "2018"

[[bin]]
name = "ping"
path = "src/ping.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
